#ifndef ZE_HS_RETORTS_H_9E5E6DE4
#define ZE_HS_RETORTS_H_9E5E6DE4

#include "libLoam/c/ob-retorts.h"
#include "libLoam/c/ob-types.h"

/* FIXME: remove this (temporary hack) */
#ifndef OB_RETORTS_HASKELL_FIRST
#define OB_RETORTS_HASKELL_FIRST OB_CONST_RETORT (1600000)
#endif  /* OB_RETORTS_HASKELL_FIRST */

#define ZE_HS_IOE_UNKNOWN                 -(OB_RETORTS_HASKELL_FIRST +  0)
#define ZE_HS_IOE_ALREADY_EXISTS          -(OB_RETORTS_HASKELL_FIRST +  1)
#define ZE_HS_IOE_ALREADY_IN_USE          -(OB_RETORTS_HASKELL_FIRST +  2)
#define ZE_HS_IOE_DOES_NOT_EXIST          -(OB_RETORTS_HASKELL_FIRST +  3)
#define ZE_HS_IOE_EOF                     -(OB_RETORTS_HASKELL_FIRST +  4)
#define ZE_HS_IOE_FULL                    -(OB_RETORTS_HASKELL_FIRST +  5)
#define ZE_HS_IOE_ILLEGAL_OPERATION       -(OB_RETORTS_HASKELL_FIRST +  6)
#define ZE_HS_IOE_PERMISSION              -(OB_RETORTS_HASKELL_FIRST +  7)
#define ZE_HS_IOE_RESOURCE_VANISHED       -(OB_RETORTS_HASKELL_FIRST +  8)
#define ZE_HS_IOE_USER                    -(OB_RETORTS_HASKELL_FIRST +  9)
#define ZE_HS_IOE_HARDWARE_FAULT          -(OB_RETORTS_HASKELL_FIRST + 10)
#define ZE_HS_IOE_INAPPROPRIATE_TYPE      -(OB_RETORTS_HASKELL_FIRST + 11)
#define ZE_HS_IOE_INTERRUPTED             -(OB_RETORTS_HASKELL_FIRST + 12)
#define ZE_HS_IOE_INVALID_ARGUMENT        -(OB_RETORTS_HASKELL_FIRST + 13)
#define ZE_HS_IOE_PROTOCOL_ERROR          -(OB_RETORTS_HASKELL_FIRST + 14)
#define ZE_HS_IOE_SYSTEM_ERROR            -(OB_RETORTS_HASKELL_FIRST + 15)
#define ZE_HS_IOE_TIMEOUT                 -(OB_RETORTS_HASKELL_FIRST + 16)
#define ZE_HS_IOE_UNSATISFIED_CONSTRAINTS -(OB_RETORTS_HASKELL_FIRST + 17)
#define ZE_HS_IOE_UNSUPPORTED_OPERATION   -(OB_RETORTS_HASKELL_FIRST + 18)

#define ZE_HS_ALREADY_CLOSED              -(OB_RETORTS_HASKELL_FIRST + 100)

const char *ze_hs_ioe_error_string (ob_retort err);

#endif /* ZE_HS_RETORTS_H_9E5E6DE4 */
