#ifndef ZE_HS_RETORTS_H_9E5E6DE4
#define ZE_HS_RETORTS_H_9E5E6DE4

#include "libLoam/c/ob-retorts.h"
#include "libLoam/c/ob-types.h"

/* FIXME: remove this (temporary hack) */
#ifndef OB_RETORTS_HASKELL_FIRST
#define OB_RETORTS_HASKELL_FIRST OB_CONST_RETORT (1600000)
#endif  /* OB_RETORTS_HASKELL_FIRST */

#define IOERR_UNKNOWN                 -(OB_RETORTS_HASKELL_FIRST +  0)
#define IOERR_ALREADY_EXISTS          -(OB_RETORTS_HASKELL_FIRST +  1)
#define IOERR_ALREADY_IN_USE          -(OB_RETORTS_HASKELL_FIRST +  2)
#define IOERR_DOES_NOT_EXIST          -(OB_RETORTS_HASKELL_FIRST +  3)
#define IOERR_EOF                     -(OB_RETORTS_HASKELL_FIRST +  4)
#define IOERR_FULL                    -(OB_RETORTS_HASKELL_FIRST +  5)
#define IOERR_ILLEGAL_OPERATION       -(OB_RETORTS_HASKELL_FIRST +  6)
#define IOERR_PERMISSION              -(OB_RETORTS_HASKELL_FIRST +  7)
#define IOERR_RESOURCE_VANISHED       -(OB_RETORTS_HASKELL_FIRST +  8)
#define IOERR_USER                    -(OB_RETORTS_HASKELL_FIRST +  9)
#define IOERR_HARDWARE_FAULT          -(OB_RETORTS_HASKELL_FIRST + 10)
#define IOERR_INAPPROPRIATE_TYPE      -(OB_RETORTS_HASKELL_FIRST + 11)
#define IOERR_INTERRUPTED             -(OB_RETORTS_HASKELL_FIRST + 12)
#define IOERR_INVALID_ARGUMENT        -(OB_RETORTS_HASKELL_FIRST + 13)
#define IOERR_PROTOCOL_ERROR          -(OB_RETORTS_HASKELL_FIRST + 14)
#define IOERR_SYSTEM_ERROR            -(OB_RETORTS_HASKELL_FIRST + 15)
#define IOERR_TIMEOUT                 -(OB_RETORTS_HASKELL_FIRST + 16)
#define IOERR_UNSATISFIED_CONSTRAINTS -(OB_RETORTS_HASKELL_FIRST + 17)
#define IOERR_UNSUPPORTED_OPERATION   -(OB_RETORTS_HASKELL_FIRST + 18)

#define HSPLASMA_ALREADY_CLOSED       -(OB_RETORTS_HASKELL_FIRST + 100)
#define HSPLASMA_INTERNAL_ERROR       -(OB_RETORTS_HASKELL_FIRST + 101)

const char *ze_hs_ioe_error_string (ob_retort err);

#endif /* ZE_HS_RETORTS_H_9E5E6DE4 */
